trades:([]
	utc_datetime:`timestamp$();
	exch_datetime:`timestamp$();
	exch:`symbol$();
	sym:`symbol$();
	side:`symbol$();
	amount:`float$();
	price:`float$();
	order_id:`long$());

quotes:([]
	utc_datetime:`timestamp$();
	exch_datetime:`timestamp$();
	exch:`symbol$();
	sym:`symbol$();
	bnum:`int$();
	bsize:`float$();
	bid:`float$();
	ask:`float$();
	asize:`float$();
	anum:`int$())
